security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    acl:
        connection: default

    role_hierarchy:
        ROLE_FARMER:      ROLE_USER
        ROLE_ADMIN:       ROLE_FARMER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /farm
                always_use_default_target_path: true
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/_console, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/farm/new, role: ROLE_USER }
        - { path: ^/farm/, role: ROLE_FARMER }
        - { path: ^/admin/, role: ROLE_ADMIN }

